Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -21,9 +21,11 @@ jobs:
     - name: Run Simple_line_plot.py and generate output
       run: |
         python Simple_line_plot.py
-    - name: Upload output file as an artifact
-      uses: actions/upload-artifact@v3
-      with:
-        name: output-file
-        path: ./output.png 
+    - name: Commit and push if there's a new output
+      run: |
+        git config --local user.email "tbxbush@gmail.com"
+        git config --local user.name "lingeshperakasam"
+        git add -f output.png
+        git commit -m "Add generated output file" || exit 0   # This will not fail if there's nothing to commit
+        git push
 
